version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

  pre_build:
    commands:
      - echo "Deploying infrastructure with CloudFormation..."
      - aws cloudformation deploy --template-file infrastructure/aws/cloudformation.yml --stack-name ecommerce-dissertation --parameter-overrides KeyName=ecommerce-key --capabilities CAPABILITY_NAMED_IAM
      - echo "Waiting for EC2 instance to be ready..."
      - aws cloudformation wait stack-create-complete --stack-name ecommerce-dissertation

  build:
    commands:
      - echo "Building application..."
      - cd backend && npm ci && cd ..
      - cd frontend && npm ci && npm run build && cd ..

  post_build:
    commands:
      - echo "Deploying application to EC2..."
      - echo "Current directory: $(pwd)"
      - echo "Listing scripts directory:"
      - ls -la scripts/
      - chmod +x scripts/deploy.sh
      - ./scripts/deploy.sh

artifacts:
  files:
    - '**/*'
  base-directory: frontend/build
