version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Checking Node & npm versions..."
      - node --version
      - npm --version

  pre_build:
    commands:
      - echo "Installing backend dependencies..."
      - cd backend && npm install && cd ..
      - echo "Installing frontend dependencies..."
      - cd frontend && npm install && cd ..

  build:
    commands:
      - echo "Building frontend..."
      - cd frontend && npm run build && cd ..
      - echo "Backend is ready (no build step needed)."

  post_build:
    commands:
      - echo "Build phase completed successfully."

artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    frontend:
      base-directory: frontend/build
      files:
        - '**/*'
    backend:
      base-directory: backend
      files:
        - '**/*'

