
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Using Node $(node -v) and npm $(npm -v)"
      - npm install -g npm@latest
      - echo "Install phase complete"

  pre_build:
    commands:
      - echo "Installing backend dependencies..."
      - cd backend
      - npm ci
      - cd ..
      - echo "Installing frontend dependencies..."
      - cd frontend
      - rm -rf node_modules package-lock.json
      - npm install
      - cd ..
      - echo "Pre-build phase complete"

  build:
    commands:
      - echo "Building frontend..."
      - cd frontend
      - npx react-scripts build
      - cd ..
      - echo "Build phase complete"

artifacts:
  files:
    - backend/**
    - frontend/build/**  # Will now work since the build is recreated

