version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "=== Installing dependencies ==="
      - cd backend && npm install
      - cd ../frontend && npm install
      - echo "=== Building frontend ==="
      - cd ../frontend && npm run build
      - echo "🎉 BUILD SUCCESSFUL - READY FOR DEPLOYMENT ==="

artifacts:
  files:
    - "**/*"
