version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - cd dissertation-ecommerce/backend && npm install
      - cd ../frontend && npm install

  build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - "**/*"
  base-directory: dissertation-ecommerce
