version: 0.2

phases:
  build:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "=== Starting build process ==="
      - echo "Current directory:"
      - pwd
      - echo "=== Installing backend ==="
      - cd backend && npm install
      - echo "=== Installing frontend ==="
      - cd ../frontend && npm install
      - echo "=== Running tests ==="
      - cd ../backend && npm test
      - echo "=== Building frontend ==="
      - cd ../frontend && npm run build
      - echo "🎉 ALL STEPS COMPLETED SUCCESSFULLY ==="

artifacts:
  files:
    - "**/*"
