
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "=== DEBUG: Listing directory structure ==="
      - pwd
      - ls -la
      - echo "=== Installing dependencies ==="
      - ls -la backend/ || echo "Backend folder not found"
      - ls -la frontend/ || echo "Frontend folder not found"
      - cd backend && npm install
      - cd ../frontend && npm install

  pre_build:
    commands:
      - echo "=== Running tests ==="
      - pwd
      - ls -la
      - cd backend && npm test

  build:
    commands:
      - echo "=== Building frontend ==="
      - cd frontend && npm run build

artifacts:
  files:
    - '**/*'
  base-directory: .
