
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "=== Finding project root ==="
      - PROJECT_ROOT=$(find . -name "backend" -type d | head -1 | xargs dirname)
      - echo "Project root: $PROJECT_ROOT"
      - cd "$PROJECT_ROOT/backend" && npm install
      - cd "$PROJECT_ROOT/frontend" && npm install

  pre_build:
    commands:
      - PROJECT_ROOT=$(find . -name "backend" -type d | head -1 | xargs dirname)
      - cd "$PROJECT_ROOT/backend" && npm test

  build:
    commands:
      - PROJECT_ROOT=$(find . -name "backend" -type d | head -1 | xargs dirname)
      - cd "$PROJECT_ROOT/frontend" && npm run build

artifacts:
  files:
    - '**/*'
  base-directory: $PROJECT_ROOT
