version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "=== Starting build ==="
      - echo "Current directory:"
      - pwd
      - echo "=== Backend ==="
      - (cd backend && npm install)
      - echo "=== Frontend ==="
      - (cd frontend && npm install && npm run build)
      - echo "🎉 BUILD SUCCESSFUL ==="

artifacts:
  files:
    - "**/*"
