version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "=== Installing dependencies ==="
      - cd backend && npm install
      - cd ../frontend && npm ci --force
      - echo "=== Building frontend ==="
      - cd ../frontend && npm run build
      - echo "🎉 BUILD SUCCESSFUL ==="

artifacts:
  files:
    - "**/*"
