version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "=== Installing dependencies ==="
      - cd backend && npm install
      - cd ../frontend && npm install
      - echo "=== Building frontend with npx ==="
      - cd ../frontend && npx react-scripts build
      - echo "🎉 BUILD SUCCESSFUL ==="

artifacts:
  files:
    - "**/*"
